// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_die_100_times = "CgkI0Mnw4d0YEAIQDA"; // <GPGSID>
        public const string achievement_the_light_at_the_end_of_the_tunnel = "CgkI0Mnw4d0YEAIQCA"; // <GPGSID>
        public const string achievement_budding_archaeologist = "CgkI0Mnw4d0YEAIQBA"; // <GPGSID>
        public const string achievement_gold_digger = "CgkI0Mnw4d0YEAIQBQ"; // <GPGSID>
        public const string achievement_welcome_among_us = "CgkI0Mnw4d0YEAIQAQ"; // <GPGSID>
        public const string achievement_ouch = "CgkI0Mnw4d0YEAIQCQ"; // <GPGSID>
        public const string achievement_die_50_times = "CgkI0Mnw4d0YEAIQCw"; // <GPGSID>
        public const string achievement_die_25_times = "CgkI0Mnw4d0YEAIQCg"; // <GPGSID>
        public const string achievement_a_lack_of_equilibrium = "CgkI0Mnw4d0YEAIQAw"; // <GPGSID>
        public const string achievement_franko_would_be_proud = "CgkI0Mnw4d0YEAIQBw"; // <GPGSID>
        public const string achievement_hardstuck = "CgkI0Mnw4d0YEAIQDQ"; // <GPGSID>
        public const string achievement_the_feeling_of_a_job_well_done = "CgkI0Mnw4d0YEAIQBg"; // <GPGSID>

}

