// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_ouch = "CgkI0Mnw4d0YEAIQEA"; // <GPGSID>
        public const string achievement_beta_tester = "CgkI0Mnw4d0YEAIQHA"; // <GPGSID>
        public const string achievement_step_saver = "CgkI0Mnw4d0YEAIQGQ"; // <GPGSID>
        public const string achievement_beggining_of_a_long_journey = "CgkI0Mnw4d0YEAIQDw"; // <GPGSID>
        public const string achievement_lost_cause = "CgkI0Mnw4d0YEAIQEg"; // <GPGSID>
        public const string achievement_budding_archaeologist = "CgkI0Mnw4d0YEAIQFg"; // <GPGSID>
        public const string achievement_bloup_bloup_bloup = "CgkI0Mnw4d0YEAIQFA"; // <GPGSID>
        public const string achievement_unhealthy = "CgkI0Mnw4d0YEAIQGg"; // <GPGSID>
        public const string achievement_laziness_or_talent = "CgkI0Mnw4d0YEAIQGw"; // <GPGSID>
        public const string achievement_welcome_among_us = "CgkI0Mnw4d0YEAIQFQ"; // <GPGSID>
        public const string achievement_francko_would_be_proud = "CgkI0Mnw4d0YEAIQHQ"; // <GPGSID>
        public const string achievement_lack_of_balance = "CgkI0Mnw4d0YEAIQEw"; // <GPGSID>
        public const string achievement_where_are_they_all = "CgkI0Mnw4d0YEAIQFw"; // <GPGSID>
        public const string achievement_you_need_to_get_better = "CgkI0Mnw4d0YEAIQEQ"; // <GPGSID>
        public const string achievement_gold_digger = "CgkI0Mnw4d0YEAIQGA"; // <GPGSID>

}

